### ISSUE TITLE
Context needed

### ISSUE THREAD

**Issue by rakekniven** [rotdrop/nextcloud-roundcube#12]
https://github.com/rotdrop/nextcloud-roundcube/blob/52cba8d4e634dff546ceff3c6288c08dbef8f8b6/src/toolkit/util/ajax.js#L93

Requested at Transifex.

**Comment by rotdrop** [comment]
Well, this is a translation for HTTP status code 506. So at least the hint with the status code should be placed before each line. Or maybe just move this out of the translatable space. I will now first check if this is needed at all (if not then my apologies for introducing useless work).

Kind thanks for reporting!

**Comment by rotdrop** [comment]
Sorry, there was a typo in .l10nignore:

https://github.com/rotdrop/nextcloud-roundcube/blob/5ac3b2c8df11d9cda3410f154b0be91f8276dd66/.l10nignore#L9

This should have been `src/toolkit/util/`

This is now fixed by commit f5165224b5e9c3fa181524b4c1d4985c31ffd66a. I have also added some more folders to the ignore list.

**Comment by rotdrop** [comment]
... there may be similar issues some of my other apps (pdf_download, files_archive, dokuwiki). I'll address this shortly.

**Comment by silopolis** [comment]
Thank you @rakekniven for reporting and @rotdrop for fixing this.
And yes, the exact same issue appears in a couple of other resources among which pdf_downloader.

**Comment by rotdrop** [comment]
I have just committed some changes for the other apps by adding some folders to the ignore list and by adding comments to that `ajax.js` file. Another option would be to not translate the textual description of the HTTP status codes.

**Comment by silopolis** [comment]
> Another option would be not to translate the textual description of the HTTP status codes.

That's a tricky one. I'm still to fresh in the translation game to have a justified opinion :/

**Comment by rotdrop** [comment]
> > Another option would be not to translate the textual description of the HTTP status codes.
> 
> That's a tricky one. I'm still to fresh in the translation game to have a justified opinion :/

Supposedly this decision is up to me. Actually, before I started to move some of my private hacks or apps to the NC app-store I also used GNU gettext to maintain (German) translations for myself. In that context it did not matter as the only involved person was me and I could just leave out a translation which did not seem so important.

The status texts may also popup in other contexts, so it probably is not the worst thing in the world to keep them in the pool of translatable strings.

I will check by tomorrow whether my comments made it into the Transifex database.  They read like this:

```
// TRANSLATORS: HTTP status-code 200, see e.g. https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
200: t(appName, 'OK'),
```

Probably "Textual description of HTTP status-code ..." would be better.

**Comment by rotdrop** [comment]
> Actually I see no string with comments at TX.

Thanks for the notice, I did not yet find the time to check this.

It seems then than things work slightly different between PHP and Javascript. I'll have a look.

**Comment by rotdrop** [comment]
Ok, at least the comments are there in the pdf_downloader resource, see screenshot. Also, this stuff has vanished from mail_roundcube as it is not used there.
![Screenshot_20230304_154108](https://user-images.githubusercontent.com/1494769/222909095-50f59398-9d63-41b5-8f1a-bd3364dc7b6b.png)

**Comment by rotdrop** [comment]
> > It seems then than things work slightly different between PHP and Javascript.
> 
> Are you aware of https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#provide-context-hints-for-translators ?

In a sense yes, because I had used the correct `// TRANSLATORS ...` syntax as the comments are there at TX.

So coming back to your previous comment: which resource is still missing these comments? They are not needed anymore for **this** app as the strings in question have been excluded from the pool of l10n strings of this app.

Perhaps an automatic bridge from the Transifex discussions would be helpful. I is of course not my goal to be a reason of frustration for the translators team, but is also difficult to monitor the discussions attached to the individual strings.

Is there a possibility to get an automatic notification for new TX comments, best for all comments of a specific resource?
